### ISSUE TITLE
Fix relative Filepaths

### ISSUE THREAD

**Issue by pbatroff** [civicrm/org.civicrm.mosaicomsgtpl#13]
When copying mosaico templates to classic message templates, relative filepaths seem to fail, mainly social media icons. There was a discussion on this problem in the mosaico extension issue tracker, see [182](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/pull/182) and [160](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/160).

I think a replication on the filterHtml funciton in UrlFilter.php in the mosaico extension can fix this. it replaces relative Paths with absolute paths, and as long as the template is available this should work.

I tested/experienced the problem with the [versafix-1.1](https://github.com/voidlabs/versafix-template) template, but I'm fairly sure that it will happen with default versafix-1 template as well. I'll test this and update the issue.

**Comment by pbatroff** [comment]
created a PR [here](https://github.com/civicrm/org.civicrm.mosaicomsgtpl/pull/15)

**Comment by MikeyMJCO** [comment]
Resolved by #15
