### ISSUE TITLE
Uninstall not removing synchronized templates

### ISSUE THREAD

**Issue by shaneonabike** [civicrm/org.civicrm.mosaicomsgtpl#21]
Hey thanks for making this plugin.

I noticed that when I uninstall it still keeps the templates in the User-drive message section. I was thinking it would remove them from there. How can I go about taking them out since there is no delete capacity?

Thanks!

**Comment by MikeyMJCO** [comment]
The current master will delete the Templates when the corresponding mosaico template is deleted. If you reinstall you should be able to delete from API explorer as well. We should definitely add removing on uninstall to the features.

**Comment by shaneonabike** [comment]
Yeah in my case I had only wanted to synchronize one template, but it synchronized all of them. So I think my client won't understand why the others were there. I figured through an uninstall it would just remove them. Thanks for the feature consideration that would be awesome. I'll take a look through the API in the meantime.

**Comment by MikeyMJCO** [comment]
I'm going to open an issue on GitLab for this since we're archiving this GitHub and moving development to https://lab.civicrm.org/extensions/mosaicomsgtpl :-)

**Comment by shaneonabike** [comment]
/slaps forehead... so sorry I cloned this from gitlab and wrote the ticket here..
