### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by gcpower** [civicrm/org.civicrm.mosaicomsgtpl#4]
Version 5.60.  
Steps to reproduce 
Downloaded compressed file to ext directory and unpacked.  Selected install from CiviCRM Extensions.  Install failed with following error message
```
$backTrace = #0 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Error.php(381): CRM_Core_Error::backtrace("backTrace", TRUE) 
#1 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Controller.php(833): CRM_Core_Error::fatal("We can't load the requested web page. This page requires cookies to be enable...")
#2 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Controller.php(828): CRM_Core_Controller->invalidKeyCommon() 
#3 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Controller.php(312): CRM_Core_Controller->invalidKey() 
#4 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Controller.php(204): CRM_Core_Controller->key("CRM_Admin_Form_MessageTemplates", TRUE, FALSE)
#5 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Controller/Simple.php(66): CRM_Core_Controller->__construct("Message Templates", TRUE, NULL, "CRM_Admin_Form_MessageTemplates", TRUE, FALSE) 
#6 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Utils/Wrapper.php(83): CRM_Core_Controller_Simple->__construct("CRM_Admin_Form_MessageTemplates", "Message Templates", NULL, FALSE, FALSE, FALSE, FALSE) 
#7 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(282): CRM_Utils_Wrapper->run("CRM_Admin_Form_MessageTemplates", "Message Templates", (Array:0)) 
#8 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:14))
#9 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:4)) 
#10 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:4)) 
#11 /home/webdevelopmentsc/public_html/includes/menu.inc(527): civicrm_invoke("admin", "messageTemplates", "add")
#12 /home/webdevelopmentsc/public_html/index.php(21): menu_execute_active_handler() 
#13 {main}
```

**Comment by MikeyMJCO** [comment]
Can you try clearing your CiviCRM cache - I'm unable to reproduce this on 5.6.0

**Comment by gcpower** [comment]
I cleared the CiviCRM cache and error occurred.  I repeated and same problem.  This is the error output

#0 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Admin/Form/Extensions.php(190): civicrm_api3("Extension", "install", (Array:2))
#1 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Form.php(489): CRM_Admin_Form_Extensions->postProcess()
#2 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/StateMachine.php(160): CRM_Core_Form->mainProcess()
#3 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next")
#4 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next")
#5 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next")
#6 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("next")
#7 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(398): CRM_Core_Controller->run()
#8 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(156): CRM_Core_Page_Basic->edit(1, NULL)
#9 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Admin/Page/Extensions.php(121): CRM_Core_Page_Basic->run()
#10 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(309): CRM_Admin_Page_Extensions->run((Array:3), NULL)
#11 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:16))
#12 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#13 /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:3))
#14 /home/webdevelopmentsc/public_html/includes/menu.inc(527): civicrm_invoke("admin", "extensions")
#15 /home/webdevelopmentsc/public_html/index.php(21): menu_execute_active_handler()
#16 

> {main}

>

**Comment by MikeyMJCO** [comment]
So that's a different error. Can you provide more of the log please - there should be a section before the backtrace with an error message.

**Comment by gcpower** [comment]
There is a large error log.  I have attached it as a pdf file.
[error log mosaico.pdf](https://github.com/civicrm/org.civicrm.mosaicomsgtpl/files/2469871/error.log.mosaico.pdf)

**Comment by MikeyMJCO** [comment]
Thanks :-)

Unfortunately that error log shows me that it's complaining about a DB Missing Field - but doesn't include what field it's looking for which is usually earlier in the log. Are you able to find this?

**Comment by gcpower** [comment]
Apologies for the delay in replying.  I am now on my way home.  I reran the install and copied the four errors in the log file.  I hope this helps.
[error log mosaico 2.pdf](https://github.com/civicrm/org.civicrm.mosaicomsgtpl/files/2470606/error.log.mosaico.2.pdf)

**Comment by MikeyMJCO** [comment]
Thanks @gcpower - I'll dive into these as soon as I can! I think I've got what I need there!

**Comment by MikeyMJCO** [comment]
Can you confirm your CiviCRM & Mosaico version.

**Comment by MikeyMJCO** [comment]
Can you bring your Mosaico version up to the official "beta4" version? Matt's forked beta3 is behind the official beta3 and the current beta4.

**Comment by gcpower** [comment]
Perfect.  Thank you very much.  Now installed without errors.
