### ISSUE TITLE
Add settings/filter for synchronization

### ISSUE THREAD

**Issue by pbatroff** [civicrm/org.civicrm.mosaicomsgtpl#8]
It should be possible to disable global synchronization, or synchronize just a configurable set of templates.

I would work on a small PR for this.

First steps would be

1. Create Settings page for Extension
2. prevent global synchronization (thus only manual api calls are possible)
3. on the settings page, show all mosaico templates and enable synchronization
4. add subject to the template
5. show differences to message templates --> if global sync is turned off, you can manually sync tempates if needed

**Comment by MikeyMJCO** [comment]
Hi @pbatroff,

I'm sure I speak for both @artfulrobot and myself when I say we'd be happy to review such a PR.

**Comment by MikeyMJCO** [comment]
If there's anything you need in the way of help or testing please let us know - if you're able to write unit tests to go along with your changes this would be helpful - we're aiming to have this module fully unit tested where possible.

**Comment by pbatroff** [comment]
I'm working on a 2 step progress to integrate settings.

First step is to list all synced templates, and add a custom subject to it, second step is to list all templates and add a checkbox to decide which templates will be synced.

Once that is done, I will prepare a PR for this, since it already is some code.

**Comment by pbatroff** [comment]
I'm still active here, and it's working well with the regular Expression for the templates. There is a settings page handling that. 

Currently there is no time/funding to get a selector for all templates, which was the original idea. Ideally there would be a list of all available templates, and I can activate the templates that I want to sync. I hope I'll be able to implement this end of the year.

**Comment by MikeyMJCO** [comment]
Closed for move to GL
